# Generated by Django 3.2.4 on 2021-06-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='user',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='user',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='voicemailscript',
            old_name='user',
            new_name='agent',
        ),
    ]
