# Generated by Django 3.2.4 on 2021-06-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_auto_20210614_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorcohort',
            name='sponsors',
            field=models.ManyToManyField(to='theapp.Account'),
        ),
    ]
