# Generated by Django 3.2.4 on 2021-06-15 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_alter_sponsorcohort_sponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
    ]
