# Generated by Django 3.2.4 on 2021-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_remove_note_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorcohort',
            name='active',
        ),
        migrations.AddField(
            model_name='account',
            name='needs_sponsors',
            field=models.BooleanField(default=False),
        ),
    ]
