# Generated by Django 3.2.4 on 2021-06-15 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0005_auto_20210615_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorcohort',
            old_name='course_name',
            new_name='test',
        ),
    ]
