# Generated by Django 3.2.4 on 2021-06-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0006_rename_course_name_sponsorcohort_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorcohort',
            name='test',
        ),
        migrations.AddField(
            model_name='sponsorcohort',
            name='course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
