# Generated by Django 3.2.4 on 2021-06-15 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0007_auto_20210615_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='converted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
