# Generated by Django 3.2.4 on 2021-06-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0009_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorcohort',
            name='course_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
