# Generated by Django 3.2.4 on 2021-06-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0010_alter_sponsorcohort_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='agent',
            field=models.CharField(max_length=300),
        ),
    ]
