# Generated by Django 3.2.4 on 2021-06-16 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theapp', '0011_alter_supportticket_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
