# Generated by Django 3.2.4 on 2021-06-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0014_admintask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='called_once',
        ),
        migrations.RemoveField(
            model_name='account',
            name='called_twice',
        ),
    ]
