# Generated by Django 3.2.4 on 2021-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0018_alter_document_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
