# Generated by Django 3.2.4 on 2021-06-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0021_leadpdf_prospect_timetask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prospect',
        ),
    ]
