# Generated by Django 3.2.4 on 2021-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0022_delete_prospect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='converted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
