# Generated by Django 3.2.4 on 2021-06-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0026_remove_timerecord_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
