# Generated by Django 3.2.4 on 2021-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0027_auto_20210623_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
