# Generated by Django 3.2.4 on 2021-06-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0028_timerecord_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='task_desc',
        ),
    ]
